// frontend/src/components/common/ErrorBoundary.vue
<template>
  <div v-if="error" class="min-h-screen flex items-center justify-center px-4 bg-gray-50 dark:bg-dark-bg">
    <div class="max-w-md w-full text-center">
      <!-- Error icon -->
      <div class="mb-6">
        <div class="w-20 h-20 bg-danger/10 rounded-full flex items-center justify-center mx-auto">
          <i class="fas fa-exclamation-triangle text-danger text-3xl"></i>
        </div>
      </div>
      
      <!-- Error message -->
      <h1 class="text-2xl font-bold text-gray-900 dark:text-dark-text mb-2">
        Oops! Algo deu errado
      </h1>
      <p class="text-gray-600 dark:text-gray-400 mb-6">
        {{ errorMessage }}
      </p>
      
      <!-- Error details (dev mode) -->
      <details v-if="isDev && errorStack" class="text-left mb-6">
        <summary class="cursor-pointer text-sm text-gray-500 hover:text-gray-700 mb-2">
          Detalhes técnicos
        </summary>
        <pre class="bg-gray-100 dark:bg-dark-card p-4 rounded-lg text-xs overflow-auto max-h-60">{{ errorStack }}</pre>
      </details>
      
      <!-- Actions -->
      <div class="space-y-3">
        <BaseButton
          variant="primary"
          size="lg"
          full-width
          @click="handleReload"
        >
          <i class="fas fa-redo mr-2"></i>
          Tentar Novamente
        </BaseButton>
        
        <BaseButton
          variant="outline"
          size="lg"
          full-width
          @click="handleGoHome"
        >
          <i class="fas fa-home mr-2"></i>
          Voltar ao Início
        </BaseButton>
      </div>
      
      <!-- Support -->
      <p class="text-sm text-gray-500 mt-8">
        Se o problema persistir, entre em contato com o suporte:
        <a href="mailto:support@findmydoc.co.mz" class="text-primary hover:underline">
          support@findmydoc.co.mz
        </a>
      </p>
    </div>
  </div>
  
  <slot v-else></slot>
</template>

<script setup lang="ts">
import { ref, onErrorCaptured } from 'vue'
import { useRouter } from 'vue-router'
import BaseButton from './BaseButton.vue'

const router = useRouter()

const error = ref(false)
const errorMessage = ref('Encontramos um problema inesperado. Por favor, tente novamente.')
const errorStack = ref('')
const isDev = import.meta.env.DEV

onErrorCaptured((err: Error) => {
  error.value = true
  errorMessage.value = err.message || errorMessage.value
  errorStack.value = err.stack || ''
  
  // Log to console in dev mode
  if (isDev) {
    console.error('ErrorBoundary caught:', err)
  }
  
  // Send to error tracking service in production
  if (!isDev) {
    // TODO: Send to Sentry, LogRocket, etc.
    console.error('Production error:', err)
  }
  
  // Prevent error from propagating
  return false
})

const handleReload = () => {
  error.value = false
  errorMessage.value = ''
  errorStack.value = ''
  window.location.reload()
}

const handleGoHome = () => {
  error.value = false
  errorMessage.value = ''
  errorStack.value = ''
  router.push('/')
}
</script>

// src/app/error-boundary.tsx
import React, { Component, ErrorInfo, ReactNode } from 'react';
import { AlertCircle, RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Card, CardContent } from '@/components/ui/Card';

interface Props {
  children: ReactNode;
  fallback?: ReactNode;
}

interface State {
  hasError: boolean;
  error?: Error;
  errorInfo?: ErrorInfo;
}

export class ErrorBoundary extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = { hasError: false };
  }

  public static getDerivedStateFromError(error: Error): State {
    return { hasError: true, error };
  }

  public componentDidCatch(error: Error, errorInfo: ErrorInfo) {
    console.error('Error caught by boundary:', error, errorInfo);
    this.setState({ error, errorInfo });
  }

  private handleRetry = () => {
    this.setState({ hasError: false, error: undefined, errorInfo: undefined });
  };

  private handleReload = () => {
    window.location.reload();
  };

  public render() {
    if (this.state.hasError) {
      if (this.props.fallback) {
        return this.props.fallback;
      }

      return (
        <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900 p-4">
          <Card className="max-w-md w-full">
            <CardContent className="text-center">
              <div className="mb-6">
                <AlertCircle className="h-12 w-12 text-error-500 mx-auto mb-4" />
                <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-2">
                  Oops! Algo deu errado
                </h2>
                <p className="text-gray-600 dark:text-gray-400">
                  Ocorreu um erro inesperado. Tente novamente ou recarregue a página.
                </p>
              </div>

              {process.env.NODE_ENV === 'development' && this.state.error && (
                <div className="mb-6 p-3 bg-gray-100 dark:bg-gray-800 rounded text-left text-xs">
                  <details>
                    <summary className="cursor-pointer font-medium text-gray-700 dark:text-gray-300">
                      Error Details (Development Only)
                    </summary>
                    <pre className="mt-2 text-red-600 dark:text-red-400 overflow-auto">
                      {this.state.error.toString()}
                      {this.state.errorInfo?.componentStack}
                    </pre>
                  </details>
                </div>
              )}

              <div className="flex gap-3 justify-center">
                <Button 
                  variant="outline" 
                  onClick={this.handleRetry}
                  leftIcon={<RefreshCw className="h-4 w-4" />}
                >
                  Tentar Novamente
                </Button>
                <Button 
                  variant="primary" 
                  onClick={this.handleReload}
                >
                  Recarregar Página
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      );
    }

    return this.props.children;
  }
}

// Hook version for functional components
export const useErrorHandler = () => {
  const handleError = (error: Error, errorInfo?: ErrorInfo) => {
    console.error('Error handled:', error, errorInfo);
    
    // You can send to error reporting service here
    // e.g., Sentry, LogRocket, etc.
  };

  return handleError;
};
